# Fase 3 Projeto FIAP

### Modelagem e Manipulação de Dados

In [ ]:
import pandas as pd
import numpy as np

# Data visualization library
import pygwalker as pyg

In [ ]:
# Read and manipulation data

flights_df = pd.read_csv("../data/bronze/flights.csv", sep=",")
airlines_df = pd.read_csv("../data/bronze/airlines.csv", sep=",")
airports_df = pd.read_csv("../data/bronze/airports.csv", sep=",")

/var/folders/h0/9cxt3flx6px_mz8j5myq3cjw0000gn/T/ipykernel_14371/3539612395.py:3: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  flights_df = pd.read_csv("../data/bronze/flights.csv", sep=",")

-----

#### Manipulation Flights Database

In [ ]:
flights_df.head(10)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,1,1,4,DL,806,N3730B,SFO,MSP,25,...,610.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,1,1,4,NK,612,N635NK,LAS,MSP,25,...,509.0,-17.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,1,1,4,US,2013,N584UW,LAX,CLT,30,...,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,...,532.0,-13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,1,1,4,DL,1173,N826DN,LAS,ATL,30,...,656.0,-15.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
flights_df["DATE"] = pd.to_datetime(
    flights_df["YEAR"].astype(str) + "-" +
    flights_df["MONTH"].astype(str) + "-" +
    flights_df["DAY"].astype(str),
    format="%Y-%m-%d"
)

In [ ]:
flights_df.drop(columns=[
    "YEAR",
    "MONTH",
    "DAY"
], inplace=True)

#### Manipulação nas colunas de HHMM, segue abaixo quais são:

- SCHEDULED_DEPARTURE: Horário de partida programado
- DEPARTURE_TIME: Horário real de partida
- WHEELS_OFF: Horário em que o avião decolou 
- WHEELS_ON: Horário em que as rodas tocaram o solo
- SCHEDULED_ARRIVAL: Horário de chegada programado 
- ARRIVAL_TIME: Horário de chegada real

In [ ]:
# Excluido as colunas que não precisam:
flights_df.drop(columns=[
    "WHEELS_OFF",
    "WHEELS_ON"
], inplace=True)

In [ ]:
# Colunas que possuem NA e o total:

columns_hhmm = [
    "SCHEDULED_DEPARTURE",
    "SCHEDULED_ARRIVAL",
    "DEPARTURE_TIME",
    "ARRIVAL_TIME"
]


for column in columns_hhmm:
    somatorio = flights_df[column].isna().sum()
    print(f"{column}: {somatorio}")

    if somatorio > 0:
        flights_df[column] = flights_df[column].fillna(0)
        flights_df[column] = flights_df[column].astype(int)

        print(f"Coluna {column} alterada para int, total NaN {flights_df[column].isna().sum()}")

SCHEDULED_DEPARTURE: 0
SCHEDULED_ARRIVAL: 0
DEPARTURE_TIME: 86153
Coluna DEPARTURE_TIME alterada para int, total NaN 0
ARRIVAL_TIME: 92513
Coluna ARRIVAL_TIME alterada para int, total NaN 0

In [ ]:
flights_df["DISTANCE_KM"] = (flights_df["DISTANCE"] * 1.60934).round(0)

In [ ]:

descricao_cancelamentos = {
    "A": "Airline",
    "B": "Weather",
    "C": "NAS",
    "D": "Security"
}

flights_df["CANCELLATION_DESCRIPTION"] = flights_df["CANCELLATION_REASON"].map(descricao_cancelamentos)

flights_df["CANCELLATION_DESCRIPTION"] = flights_df["CANCELLATION_DESCRIPTION"].fillna("N/A")

In [ ]:
dias_semana = {
    1: "Segunda-feira",
    2: "Terça-feira",
    3: "Quarta-feira",
    4: "Quinta-feira",
    5: "Sexta-feira",
    6: "Sábado",
    7: "Domingo",
}

flights_df["WEEKDAY_NAME"] = flights_df["DAY_OF_WEEK"].map(dias_semana)

In [ ]:
flights_df.head(10)

,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,...,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,DATE,DISTANCE_KM,CANCELLATION_DESCRIPTION,WEEKDAY_NAME
0,4,AS,98,N407AS,ANC,SEA,5,2354,-11.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,2330.0,N/A,Quinta-feira
1,4,AA,2336,N3KUAA,LAX,PBI,10,2,-8.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,3750.0,N/A,Quinta-feira
2,4,US,840,N171US,SFO,CLT,20,18,-2.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,3695.0,N/A,Quinta-feira
3,4,AA,258,N3HYAA,LAX,MIA,20,15,-5.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,3769.0,N/A,Quinta-feira
4,4,AS,135,N527AS,SEA,ANC,25,24,-1.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,2330.0,N/A,Quinta-feira
5,4,DL,806,N3730B,SFO,MSP,25,20,-5.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,2557.0,N/A,Quinta-feira
6,4,NK,612,N635NK,LAS,MSP,25,19,-6.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,2091.0,N/A,Quinta-feira
7,4,US,2013,N584UW,LAX,CLT,30,44,14.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,3420.0,N/A,Quinta-feira
8,4,AA,1112,N3LAAA,SFO,DFW,30,19,-11.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,2356.0,N/A,Quinta-feira
9,4,DL,1173,N826DN,LAS,ATL,30,33,3.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-01,2812.0,N/A,Quinta-feira

In [ ]:
flights_df.shape[0]

  AIRLINE ORIGIN_AIRPORT DESTINATION_AIRPORT
0      AS            ANC                 SEA
1      AA            LAX                 PBI
2      US            SFO                 CLT
3      AA            LAX                 MIA
4      AS            SEA                 ANC
5      DL            SFO                 MSP
6      NK            LAS                 MSP
7      US            LAX                 CLT
8      AA            SFO                 DFW
9      DL            LAS                 ATL

----

#### Merge DFs

In [ ]:
first_merge_dfs = flights_df.merge(
    airlines_df, 
    how="left", 
    left_on="AIRLINE", 
    right_on="IATA_CODE"
)

first_merge_dfs

In [ ]:
airlines_df

   IATA_CODE                       AIRLINE
0         UA         United Air Lines Inc.
1         AA        American Airlines Inc.
2         US               US Airways Inc.
3         F9        Frontier Airlines Inc.
4         B6               JetBlue Airways
5         OO         Skywest Airlines Inc.
6         AS          Alaska Airlines Inc.
7         NK              Spirit Air Lines
8         WN        Southwest Airlines Co.
9         DL          Delta Air Lines Inc.
10        EV   Atlantic Southeast Airlines
11        HA        Hawaiian Airlines Inc.
12        MQ  American Eagle Airlines Inc.
13        VX                Virgin America

In [ ]:
airports_df

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447
...,...,...,...,...,...,...,...
317,WRG,Wrangell Airport,Wrangell,AK,USA,56.48433,-132.36982
318,WYS,Westerly State Airport,West Yellowstone,MT,USA,44.68840,-111.11764
319,XNA,Northwest Arkansas Regional Airport,Fayetteville/Springdale/Rogers,AR,USA,36.28187,-94.30681
320,YAK,Yakutat Airport,Yakutat,AK,USA,59.50336,-139.66023
321,YUM,Yuma International Airport,Yuma,AZ,USA,32.65658,-114.60597