# Treinamento Supervisionado por Classificação

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/silver/flights_delay_cancelled.csv", sep=",")
df.head()

/var/folders/h0/9cxt3flx6px_mz8j5myq3cjw0000gn/T/ipykernel_5676/1577086050.py:1: DtypeWarning: Columns (4,5,31,32,33,34,37,38,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/silver/flights_delay_cancelled.csv", sep=",")

,DAY_OF_WEEK,AIRLANE_CODE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,...,ORIGIN_STATE_NAME,ORIGIN_COUNTRY_NAME,ORIGIN_LATITUDE_NAME,ORIGIN_LONGITUDE_NAME,DESTINATION_AIRPORT_NAME,DESTINATION_CITY_NAME,DESTINATION_STATE_NAME,DESTINATION_COUNTRY_NAME,DESTINATION_LATITUDE_NAME,DESTINATION_LONGITUDE_NAME
0,4,AS,98,N407AS,ANC,SEA,5,2354,-11.0,21.0,...,AK,USA,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931
1,4,AA,2336,N3KUAA,LAX,PBI,10,2,-8.0,12.0,...,CA,USA,33.94254,-118.40807,Palm Beach International Airport,West Palm Beach,FL,USA,26.68316,-80.09559
2,4,US,840,N171US,SFO,CLT,20,18,-2.0,16.0,...,CA,USA,37.61900,-122.37484,Charlotte Douglas International Airport,Charlotte,NC,USA,35.21401,-80.94313
3,4,AA,258,N3HYAA,LAX,MIA,20,15,-5.0,15.0,...,CA,USA,33.94254,-118.40807,Miami International Airport,Miami,FL,USA,25.79325,-80.29056
4,4,AS,135,N527AS,SEA,ANC,25,24,-1.0,11.0,...,WA,USA,47.44898,-122.30931,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619

#### Limpando o dataframe na qual removo das colunas categoricas, tudo que tiver numero

In [49]:
df.shape[0]

5819079

In [57]:
teste = pd.read_csv("../data/bronze/flights.csv", sep=",")
teste.shape[0]

/var/folders/h0/9cxt3flx6px_mz8j5myq3cjw0000gn/T/ipykernel_5676/2282622036.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  teste = pd.read_csv("../data/bronze/flights.csv", sep=",")

5819079

In [59]:
teste.query("DESTINATION_AIRPORT == '11298'")

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
4385712,2015,10,1,4,AA,1230,N3DBAA,14747,11298,5,...,543.0,-19.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4385720,2015,10,1,4,AA,2406,N859AA,12892,11298,15,...,510.0,-1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4385730,2015,10,1,4,AA,1746,N587UW,14107,11298,50,...,446.0,-23.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4385734,2015,10,1,4,AA,1051,N865AA,14771,11298,55,...,612.0,3.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4385738,2015,10,1,4,AA,1657,N855AA,12889,11298,59,...,524.0,-24.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4871296,2015,10,31,6,AA,116,N350AA,13830,11298,2035,...,756.0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4871374,2015,10,31,6,AA,492,N919US,14100,11298,2050,...,2326.0,-6.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4871380,2015,10,31,6,NK,720,N506NK,11292,11298,2050,...,2338.0,-1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4871532,2015,10,31,6,AA,1391,N3ASAA,13303,11298,2125,...,2320.0,-23.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4871655,2015,10,31,6,DL,29,N923DL,10397,11298,2205,...,2319.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df.query("DESTINATION_AIRPORT == '11298'")

,DAY_OF_WEEK,AIRLANE_CODE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,...,ORIGIN_COUNTRY_NAME,ORIGIN_LATITUDE_NAME,ORIGIN_LONGITUDE_NAME,DESTINATION_AIRPORT_NAME,DESTINATION_CITY_NAME,DESTINATION_STATE_NAME,DESTINATION_COUNTRY_NAME,DESTINATION_LATITUDE_NAME,DESTINATION_LONGITUDE_NAME,ATRASO
4385712,4,AA,1230,N3DBAA,14747,11298,5,15,10.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4385720,4,AA,2406,N859AA,12892,11298,15,17,2.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4385730,4,AA,1746,N587UW,14107,11298,50,43,-7.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4385734,4,AA,1051,N865AA,14771,11298,55,101,6.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4385738,4,AA,1657,N855AA,12889,11298,59,103,4.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4871296,6,AA,116,N350AA,13830,11298,2035,2029,-6.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4871374,6,AA,492,N919US,14100,11298,2050,2044,-6.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4871380,6,NK,720,N506NK,11292,11298,2050,2046,-4.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4871532,6,AA,1391,N3ASAA,13303,11298,2125,2124,-1.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4871655,6,DL,29,N923DL,10397,11298,2205,2202,-3.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

#### Considero como atraso valores acima de 15 minutos, padrão aviação

In [4]:
df["ATRASO"] = (df["DEPARTURE_DELAY"] > 15).astype(int)

df[["DEPARTURE_DELAY", "ATRASO"]]

         DEPARTURE_DELAY  ATRASO
0                  -11.0       0
1                   -8.0       0
2                   -2.0       0
3                   -5.0       0
4                   -1.0       0
...                  ...     ...
5819074             -4.0       0
5819075             -4.0       0
5819076             -9.0       0
5819077             -6.0       0
5819078             15.0       0

[5819079 rows x 2 columns]

In [5]:
df["ATRASO"].unique()

array([0, 1])

In [10]:
features = [
    "DAY_OF_WEEK",
    "AIRLANE_CODE",
    "ORIGIN_AIRPORT",
    "DESTINATION_AIRPORT",
    "SCHEDULED_DEPARTURE",
    "DISTANCE",
    "DISTANCE_KM"
]

X = df[features]
y = df["ATRASO"]

In [15]:
X.shape

(5819079, 7)

In [16]:
X.isna().sum()

DAY_OF_WEEK            0
AIRLANE_CODE           0
ORIGIN_AIRPORT         0
DESTINATION_AIRPORT    0
SCHEDULED_DEPARTURE    0
DISTANCE               0
DISTANCE_KM            0
dtype: int64

In [21]:
X.dtypes

DAY_OF_WEEK              int64
AIRLANE_CODE            object
ORIGIN_AIRPORT          object
DESTINATION_AIRPORT     object
SCHEDULED_DEPARTURE      int64
DISTANCE                 int64
DISTANCE_KM            float64
dtype: object

In [23]:
X.SCHEDULED_DEPARTURE.unique()

array([  5,  10,  20, ..., 421, 337, 409], shape=(1321,))

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [24]:
# Colunas de variáveis numéricas e categóricas
num_cols = X.select_dtypes(include=["int64", "float64"]).columns

cat_cols = X.select_dtypes(include=["object"]).columns

In [26]:
num_cols, cat_cols

(Index(['DAY_OF_WEEK', 'SCHEDULED_DEPARTURE', 'DISTANCE', 'DISTANCE_KM'], dtype='object'),
 Index(['AIRLANE_CODE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT'], dtype='object'))

In [38]:
cat_validation = X[['AIRLANE_CODE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT']]

In [39]:
cat_validation["AIRLANE_CODE"].nunique(), cat_validation["ORIGIN_AIRPORT"].nunique(), cat_validation["DESTINATION_AIRPORT"].nunique()

(14, 924, 920)

In [50]:
cat_validation["AIRLANE_CODE"].unique()

array(['AS', 'AA', 'US', 'DL', 'NK', 'UA', 'HA', 'B6', 'OO', 'EV', 'MQ',
       'F9', 'WN', 'VX'], dtype=object)

In [46]:
cat_validation["DESTINATION_AIRPORT"].unique()

array(['SEA', 'PBI', 'CLT', 'MIA', 'ANC', 'MSP', 'DFW', 'ATL', 'IAH',
       'PDX', 'MCI', 'FLL', 'ORD', 'HNL', 'PHX', 'EWR', 'JFK', 'MCO',
       'BOS', 'BDL', 'ITO', 'SFO', 'KOA', 'OGG', 'MYR', 'DTW', 'LIH',
       'DEN', 'SJU', 'LAX', 'BWI', 'IAD', 'BQN', 'BUF', 'LGA', 'HOU',
       'SLC', 'PHL', 'SJC', 'OAK', 'LGB', 'TPA', 'DCA', 'TTN', 'BTR',
       'LAS', 'RSW', 'BRD', 'STL', 'RKS', 'MBS', 'SNA', 'MEI', 'MDW',
       'SAN', 'RIC', 'AUS', 'OTZ', 'PIT', 'JAX', 'MSY', 'ONT', 'PSP',
       'BUR', 'DAL', 'CVG', 'SMF', 'RDU', 'JMS', 'BNA', 'DSM', 'MAF',
       'BOI', 'ELP', 'TUS', 'SCC', 'HPN', 'STT', 'MDT', 'RHI', 'SBP',
       'MKE', 'JNU', 'CMH', 'CLD', 'KTN', 'CAK', 'CRP', 'CLE', 'GPT',
       'SHV', 'TYS', 'IND', 'LIT', 'SAT', 'SRQ', 'TUL', 'GRK', 'PNS',
       'BTV', 'CHS', 'DAY', 'OKC', 'SAV', 'XNA', 'COS', 'GJT', 'BZN',
       'PUB', 'HRL', 'HDN', 'MEM', 'GEG', 'ORH', 'SYR', 'GSO', 'VPS',
       'LAW', 'ACY', 'LBB', 'JAC', 'BIL', 'EUG', 'ASE', 'TVC', 'MTJ',
       'CAE', 'PVD', 'HSV', 'CDC', 'YUM', 'ABQ', 'TLH', 'MLI', 'AMA',
       'EGE', 'MOB', 'JAN', 'FWA', 'MSN', 'BIS', 'MFR', 'APN', 'BHM',
       'OMA', 'LFT', 'GRR', 'MMH', 'CEC', 'SBA', 'RNO', 'CLL', 'LEX',
       'LAN', 'DLH', 'SDF', 'FAT', 'SPS', 'SGF', 'CID', 'FSM', 'MGM',
       'MFE', 'AVP', 'SJT', 'ROA', 'LRD', 'MRY', 'AGS', 'ROC', 'AEX',
       'ISN', 'MLB', 'ORF', 'ICT', 'ECP', 'PIA', 'BPT', 'ACT', 'EYW',
       'FSD', 'MLU', 'CHA', 'WRG', 'FNT', 'DIK', 'MHK', 'CNY', 'BRW',
       'GRB', 'ATW', 'SAF', 'TYR', 'MKG', 'FLG', 'FCA', 'BTM', 'EVV',
       'DRO', 'LNK', 'DBQ', 'FAR', 'OME', 'GSP', 'GUC', 'MSO', 'TXK',
       'MOT', 'RAP', 'ISP', 'PWM', 'GGG', 'SBN', 'BFL', 'MHT', 'ROW',
       'SIT', 'CMX', 'FAY', 'ILM', 'CMI', 'ALB', 'ABI', 'GTF', 'BMI',
       'COU', 'HOB', 'GNV', 'SUN', 'SPI', 'PSG', 'BRO', 'AVL', 'TOL',
       'SGU', 'GCC', 'HLN', 'CPR', 'PIH', 'BET', 'VEL', 'RDM', 'HYS',
       'PSC', 'COD', 'INL', 'FAI', 'EKO', 'BJI', 'IDA', 'IMT', 'RST',
       'HIB', 'ABR', 'STC', 'ACV', 'ESC', 'CIU', 'SWF', 'DAB', 'TRI',
       'AZO', 'CRW', 'STX', 'GRI', 'CHO', 'GCK', 'PLN', 'LSE', 'SMX',
       'RDD', 'PHF', 'LCH', 'GTR', 'LAR', 'ERI', 'PAH', 'EAU', 'LBE',
       'BLI', 'DVL', 'CWA', 'ILG', 'OAJ', 'ABE', 'ALO', 'ABY', 'DHN',
       'TWF', 'ADK', 'ELM', 'VLD', 'PIB', 'SUX', 'GUM', 'SCE', 'UST',
       'BQK', 'JLN', 'LWS', 'MQT', 'EWN', 'CSG', 'PBG', 'PSE', 'IAG',
       'YAK', 'CDV', 'OTH', 'ADQ', 'PPG', 'GFK', 'BGM', 'BGR', 'ITH',
       'ACK', 'MVY', 'WYS', 'DLG', 'AKN', 'GST', 'HYA', '11298', '13487',
       '13303', '11057', '13930', '10693', '14747', '12266', '12478',
       '14057', '10397', '13198', '12173', '11618', '13204', '12402',
       '12758', '14771', '11292', '13830', '14107', '12982', '11697',
       '12519', '13577', '14869', '12339', '13232', '11259', '15016',
       '12892', '12889', '10140', '10721', '15304', '14679', '14100',
       '10732', '10821', '14831', '14843', '14570', '12191', '11433',
       '12264', '14893', '13796', '12953', '14122', '13495', '12451',
       '11042', '11278', '14908', '13342', '13891', '10299', '12523',
       '12954', '14520', '12129', '10713', '10431', '11066', '10994',
       '10423', '10792', '14683', '10800', '10551', '11193', '14307',
       '11540', '14635', '13851', '15376', '11884', '14492', '14027',
       '13970', '13184', '13296', '10599', '11986', '14698', '11423',
       '13244', '14574', '12992', '13241', '12217', '13871', '12197',
       '11003', '15919', '14524', '14689', '10529', '14576', '11995',
       '11267', '12819', '14633', '11996', '13256', '13158', '12448',
       '10781', '13422', '16218', '15370', '10868', '14730', '13931',
       '13485', '14986', '15024', '11823', '11721', '14685', '10257',
       '12206', '12255', '12951', '14709', '14321', '12391', '14794',
       '10874', '12278', '11638', '10372', '11122', '14457', '15096',
       '12896', '11109', '10279', '11481', '15412', '14814', '11641',
       '10980', '12945', '10990', '10157', '13076', '13230', '15295',
       '10918', '13933', '11953', '10135', '14262', '11067', '13277',
       '11603', '10561', '11612', '15624', '11977', '15380', '13367',
       '14193', '10333', '11778', '11140', '14783', '10136', '14842',
       '11049', '14696', '11695', '11637', '15401', '14674', '13061',
       '10685', '11982', '10469', '11921', '14108', '11413', '12891',
       '11905', '14960', '15411', '10155', '10747', '10728', '13290',
       '13433', '10208', '11973', '15323', '10849', '13360', '13795',
       '14952', '13377', '10408', '10627', '13344', '13476', '11775',
       '10158', '11898', '13029', '15249', '11337', '12915', '15356',
       '13264', '11252', '10185', '11624', '12323', '15841', '10785',
       '11146', '14098', '10434', '12389', '15991', '11315', '11150',
       '12884', '11537', '11274', '11076', '10754', '13873', 13930, 10599,
       11697, 12266, 14492, 11298, 14869, 14683, 11278, 15016, 13244,
       11433, 12951, 13931, 11259, 10423, 14893, 11721, 12191, 14107,
       14122, 14679, 13796, 11292, 13232, 12339, 14771, 14908, 13204,
       11540, 13303, 12889, 13487, 12953, 10721, 13198, 11057, 14100,
       15304, 14828, 12982, 14057, 10136, 11193, 11042, 12173, 11618,
       15412, 13495, 15370, 10397, 14814, 11308, 10685, 11982, 14747,
       14831, 13851, 12892, 13296, 11638, 14321, 11884, 12992, 14027,
       15919, 12007, 13830, 10731, 14685, 12884, 10135, 11996, 12478,
       12217, 13485, 11973, 10792, 14730, 10800, 11986, 11481, 10821,
       10140, 10299, 14842, 10980, 12197, 10990, 12945, 10781, 11995,
       10257, 13891, 13158, 12264, 12758, 10279, 14588, 10185, 13377,
       14524, 10693, 12206, 15376, 12451, 11066, 11603, 14689, 11003,
       11267, 15607, 10994, 14635, 13342, 14576, 15096, 14986, 12278,
       12448, 10146, 14262, 10713, 14307, 15024, 10157, 13422, 10874,
       14570, 14843, 15070, 14193, 13486, 12003, 13127, 13264, 12177,
       12441, 12523, 14794, 12094, 12156, 14113, 12280, 11641, 14489,
       10849, 12896, 14256, 10561, 12954, 10620, 11097, 10779, 11122,
       10631, 12888, 15389, 15041, 14252, 12343, 12129, 11648, 10154,
       13577, 14457, 13076, 12898, 13029, 12389, 13871, 10529, 12402,
       11637, 13256, 12335, 11865, 11775, 10551, 15249, 10747, 15624,
       12391, 10208, 10926, 12819, 11423, 13367, 14952, 13277, 11980,
       11977, 11778, 15411, 13964, 11953, 11630, 11049, 11013, 11587,
       15380, 11823, 11252, 11111, 14698, 11624, 13795, 12915, 14108,
       11695, 11612, 10627, 13360, 15027, 10469, 14696, 14574, 15323,
       11203, 14633, 11337, 13241, 14098, 10408, 10155, 11146, 13061,
       14905, 13433, 11471, 14783, 10785, 11140, 12511, 12323, 10868,
       14960, 10431, 10268, 11447, 11067, 13290, 15048, 13541, 13476,
       16218, 11150, 12891, 11921, 10141, 14150, 14006, 13184, 11537,
       10434, 13230, 11617, 11525, 11898, 11109, 11867, 14711, 11577,
       12016, 14520, 14487, 10739, 14109, 10165, 11413, 10158, 15356,
       14709, 12255, 14543, 11274, 15841, 10577, 14674, 10170, 10333,
       10728, 13970, 15295, 15401, 15991, 11905, 10918, 15497, 10754,
       13344, 11503, 13459, 13873, 11315, 12519, 11076, 10581, 12265,
       14254, 10732, 10372, 13933, 14222, 14025, 13502, '12441', '14905',
       '12511', '11630', '12280', '11308', '14256', '11980', '11203',
       '11867', '12016', '14711', '11111', '12898', '14006', '15027',
       '14487', '14489', '14588', '10577', '10926', '10170', '14252',
       '12003', '13486', '10739', '14828', '12156', '10779', '11648',
       '14113', '11525', '15389', '10620', '15041', '12177', '12888',
       '13127', '13502', '10146', '14543', '11471', '12007', '10581',
       '11865', '10631', '11587', '10731', '10141', '11013', '15048',
       '14150', '14109', '11617', '15070', '11577', '15607', '12343',
       '10666', '14254'], dtype=object)

In [27]:
preprocess = ColumnTransformer(
    transformers=[
        ("num", "passthrough", num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
    ]
)

In [28]:
preprocess

ColumnTransformer(transformers=[('num', 'passthrough',
                                 Index(['DAY_OF_WEEK', 'SCHEDULED_DEPARTURE', 'DISTANCE', 'DISTANCE_KM'], dtype='object')),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 Index(['AIRLANE_CODE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT'], dtype='object'))])

In [29]:
model = LogisticRegression(max_iter=1000)

In [30]:
pipeline = Pipeline(
    steps=[
        ("preprocess", preprocess),
        ("model", model)
    ]
)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [33]:
X_train

,DAY_OF_WEEK,AIRLANE_CODE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DISTANCE,DISTANCE_KM
1165552,2,OO,RDM,SLC,1240,525,845.0
1519196,3,US,PHL,ATL,750,666,1072.0
385991,1,OO,SFO,CEC,1200,304,489.0
567775,6,B6,JAX,BOS,1219,1010,1625.0
1506100,2,EV,ORF,DTW,1105,529,851.0
...,...,...,...,...,...,...,...
5122300,1,OO,CVG,IAH,1850,871,1402.0
1893849,5,MQ,GRB,ORD,1015,173,278.0
1244476,7,AS,SEA,ABQ,1040,1180,1899.0
5374291,4,AA,IAH,MIA,800,964,1551.0
2805682,4,US,DTW,PHX,2055,1671,2689.0

In [34]:
y_train

1165552    1
1519196    0
385991     0
567775     0
1506100    0
          ..
5122300    0
1893849    0
1244476    0
5374291    0
2805682    1
Name: ATRASO, Length: 4655263, dtype: int64

In [35]:
pipeline.fit(X_train, y_train)

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']